[package]
name = "publish_crate"
version = "0.1.0"
edition = "2021"
author = "Naitik"
description = "Basic math crate"
license = "None"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
