name: "discussion verify | comments"
on:
  discussion_comment:
    types: [created]

jobs:
  create-issue:
    if: github.event.comment.body == '/create-issue'
    uses: StaytunedLLP/training/.github/workflows/comment-create-issue.yml@main
    secrets: inherit
