name: "discussion comment | /start-coding"
on:
    workflow_call:

jobs:
    dispatch-start-coding:
        runs-on: [self-hosted, pi4b-01]
        timeout-minutes: 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get issue detail
              id: get_issue_detail
              run: |
                  echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_ENV
                  echo "issue_title=${{ github.event.issue.title }}" >> $GITHUB_ENV
                  echo "issue_assignee=${{ github.event.issue.assignee.login }}" >> $GITHUB_ENV

            - name: Get Owner and Repo Name
              run: |
                  OWNER=$(echo ${{ github.repository }} | cut -d/ -f1)
                  REPO=$(echo ${{ github.repository }} | cut -d/ -f2)
                  echo "github_owner=$OWNER" >> $GITHUB_ENV
                  echo "github_repo=$REPO" >> $GITHUB_ENV

                  
            - name: Trigger event
              env:
                  APP_ID: ${{ secrets.DISPATCH_BOT_APP_ID }}
                  PRIVATE_KEY: ${{ secrets.DISPATCH_BOT_PPK }}
                  INSTALLATION_ID: ${{ secrets.DISPATCH_BOT_INSTALLATION_ID }}
                  EVENT_TYPE: start-coding
                  CLIENT_PAYLOAD: '{ "issue_number": "${{env.issue_number}}", "issue_title": "${{env.issue_title}}", "issue_assigneelogin": "${{env.issue_assignee}}" , "owner": "${{env.github_owner}}", "repo": "${{env.github_repo}}", "pr_body": "Hello world!!"}'
              run: |
                  chmod +x ./scripts/build-github-app.sh
                  docker run \
                  -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock \
                  -e APP_ID="${{env.APP_ID}}" \
                  -e PRIVATE_KEY="${{env.PRIVATE_KEY}}" \
                  -e INSTALLATION_ID="${{env.INSTALLATION_ID}}" \
                  -e EVENT_TYPE="${{env.EVENT_TYPE}}" \
                  -e CLIENT_PAYLOAD='${{env.CLIENT_PAYLOAD}}' \
                  -e REG_ADDRESS='ghcr.io/staytunedllp/gh-automation-node:latest' \
                  -e REG_USERNAME='${{github.actor}}' \
                  -e REG_PASSWORD='${{secrets.GITHUB_TOKEN}}' \
                  --rm ghcr.io/staytunedllp/dagger-in-docker:latest \
                  "dagger run ./scripts/build-github-app.sh"
