name: Create Issue
on:
  workflow_call:
    # Start coding workflow to create branch, pr and link to the issue
jobs:
  dispatch-create-issue:
    runs-on: [self-hosted, pi4b-01]
    # timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get detail
        id: get_detail
        run: |
          OWNER=$(echo ${{ github.repository }} | cut -d/ -f1)
          REPO=$(echo ${{ github.repository }} | cut -d/ -f2)
          echo "github_owner=$OWNER" >> $GITHUB_ENV
          echo "discussion_number=${{ github.event.discussion.number }}" >> $GITHUB_ENV
          echo "comment_id=${{ github.event.comment.node_id }}" >> $GITHUB_ENV
          echo "comment_repo=$REPO" >> $GITHUB_ENV
          echo "discussion_title=${{ github.event.discussion.title }}" >> $GITHUB_ENV
          echo "issue_assignee=${{ github.event.comment.user.login }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger event
        env:
          APP_ID: ${{ secrets.DISPATCH_BOT_APP_ID }}
          PRIVATE_KEY: ${{ secrets.DISPATCH_BOT_PPK }}
          INSTALLATION_ID: ${{ secrets.DISPATCH_BOT_INSTALLATION_ID }}
          EVENT_TYPE: create-issue
          CLIENT_PAYLOAD: '{"title": "Learn: ${{env.discussion_title}}","owner": "${{env.github_owner}}", "repo": "training", "number": "${{env.discussion_number}}", "assignee": "${{env.issue_assignee}}", "commentId": "${{env.comment_id}}" , "commentRepo": "${{env.comment_repo}}"}'
        run: |
          chmod +x ./scripts/build-github-app.sh
          docker run \
          -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock \
           -e APP_ID="${{env.APP_ID}}" \
           -e PRIVATE_KEY="${{env.PRIVATE_KEY}}" \
           -e INSTALLATION_ID="${{env.INSTALLATION_ID}}" \
           -e EVENT_TYPE="${{env.EVENT_TYPE}}" \
           -e CLIENT_PAYLOAD='${{env.CLIENT_PAYLOAD}}' \
           -e REG_ADDRESS='ghcr.io/staytunedllp/gh-automation-node:latest' \
           -e REG_USERNAME='${{github.actor}}' \
           -e REG_PASSWORD='${{secrets.GITHUB_TOKEN}}' \
           --rm ghcr.io/staytunedllp/dagger-in-docker:latest \
           "dagger run ./scripts/build-github-app.sh"